### ISSUE TITLE
KeyError: 'ASL-Finger-Spelling-Recognition-master'

### ISSUE THREAD

**Issue by KenGiam** [snrao310/ASL-Finger-Spelling-Recognition#6]
I got this error when I want to run the main.py
  File "main.py", line 151, in <module>
    model = trainData()
  File "main.py", line 132, in trainData
    load_data_set()
  File "main.py", line 86, in load_data_set
    y_train.append(classes[fullpath[n + 1:t]])
KeyError: 'ASL-Finger-Spelling-Recognition-master'

**Comment by arpita739** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-17-197587e9e1d1> in <module>
----> 1 model = trainData()

<ipython-input-16-0233aebba4eb> in trainData()
      3 # from disk.
      4 def trainData():
----> 5     load_data_set()
      6     a = numpy.asarray(y_train)
      7     y_train_new = a.reshape(a.shape[0], 1)

<ipython-input-13-336cf4ab80d9> in load_data_set()
      9                     img = img_to_array(img)
     10                     x_train.append(img)
---> 11                     t = fullpath.rindex('//')
     12                     fullpath = fullpath[0:t]
     13                     n = fullpath.rindex('//')

ValueError: substring not found
